terraform init
# Import of re-usable resources which can't be easily deleted. To avoid clutter.
terraform import module.akamai_property.akamai_cp_code.cp_code cpc_1271126,ctr_1-1NC95D,grp_71960
terraform import module.akamai_property.akamai_edge_hostname.my_edge_hostname ehn_5027553,ctr_1-1NC95D,grp_71960
#terraform import module.akamai_property.akamai_property.my_property prp_710964,ctr_1-1NC95D,grp_71960
terraform import module.akamai_application_security.akamai_appsec_configuration.akamai_appsec 80609
terraform import module.akamai_application_security.akamai_appsec_security_policy.security_policy 80609:qik1_167627
terraform import module.akamai_application_security.akamai_networklist_network_list.GEOBLOCKLIST 125454_GEOBLOCKLIST
terraform import module.akamai_application_security.akamai_networklist_network_list.IPBLOCKLIST 125451_IPBLOCKLIST
terraform import module.akamai_application_security.akamai_networklist_network_list.IPBLOCKLISTEXCEPTIONS 125452_IPBLOCKLISTEXCEPTIONS
terraform import module.akamai_application_security.akamai_networklist_network_list.SECURITYBYPASSLIST 125453_SECURITYBYPASSLIST
terraform import module.akamai_application_security.akamai_appsec_rate_policy.rate_policy_page_view_requests 80609:189988
terraform import module.akamai_application_security.akamai_appsec_rate_policy.rate_policy_origin_error 80609:189986
terraform import module.akamai_application_security.akamai_appsec_rate_policy.rate_policy_post_requests 80609:189987
terraform fmt