terraform init
terraform import module.akamai_application_security.akamai_networklist_network_list.GEOBLOCKLIST 125454_GEOBLOCKLIST
terraform import module.akamai_application_security.akamai_networklist_network_list.IPBLOCKLIST 125451_IPBLOCKLIST
terraform import module.akamai_application_security.akamai_networklist_network_list.IPBLOCKLISTEXCEPTIONS 125452_IPBLOCKLISTEXCEPTIONS
terraform import module.akamai_application_security.akamai_networklist_network_list.SECURITYBYPASSLIST 125453_SECURITYBYPASSLIST
terraform import module.akamai_application_security.akamai_appsec_rate_policy.rate_policy_page_view_requests 80609:189988
terraform import module.akamai_application_security.akamai_appsec_rate_policy.rate_policy_origin_error 80609:189986
terraform import module.akamai_application_security.akamai_appsec_rate_policy.rate_policy_post_requests 80609:189987
terraform fmt